/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cocogui;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author winso
 */
public class Coco extends javax.swing.JFrame {

    /**
     * Creates new form coco
     */
    public Coco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Helper = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Receiver = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        HNGOBut = new javax.swing.JButton();
        IndiBut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Register = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        RegBut = new javax.swing.JButton();
        PrevBut = new javax.swing.JButton();
        PassTxt = new javax.swing.JPasswordField();
        ConfirmPassTxt = new javax.swing.JPasswordField();
        NameTxt1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PNTxt1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        StateComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        EmailTxt1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Login = new javax.swing.JFrame();
        PassTxt1 = new javax.swing.JPasswordField();
        LogBut = new javax.swing.JButton();
        adminname = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ClearBut = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        Helper.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Helper.setTitle("helper");
        Helper.setMinimumSize(new java.awt.Dimension(370, 200));
        Helper.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                HelperWindowClosing(evt);
            }
        });
        Helper.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 204));
        jButton2.setText("Foodbank");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Helper.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 102));
        jButton4.setText("Individuals");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Helper.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hi, who you are?");
        Helper.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/MalaysiaFlag.jpg"))); // NOI18N
        Helper.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 370, 210));

        Receiver.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Receiver.setTitle("receiver");
        Receiver.setMinimumSize(new java.awt.Dimension(370, 200));
        Receiver.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Hi, who you are? ");
        Receiver.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        HNGOBut.setBackground(new java.awt.Color(0, 0, 0));
        HNGOBut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HNGOBut.setForeground(new java.awt.Color(0, 255, 102));
        HNGOBut.setText("Hospital/ NGO");
        HNGOBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HNGOButActionPerformed(evt);
            }
        });
        Receiver.getContentPane().add(HNGOBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        IndiBut.setBackground(new java.awt.Color(0, 0, 0));
        IndiBut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IndiBut.setForeground(new java.awt.Color(255, 204, 204));
        IndiBut.setText("Individuals");
        IndiBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndiButActionPerformed(evt);
            }
        });
        Receiver.getContentPane().add(IndiBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 122, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/ReceiveBackground2.jpg"))); // NOI18N
        Receiver.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 490, 290));

        Register.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Register.setTitle("Register");
        Register.setMinimumSize(new java.awt.Dimension(520, 550));
        Register.setPreferredSize(new java.awt.Dimension(520, 550));
        Register.setResizable(false);
        Register.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RegisterformWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                RegisterformWindowOpened(evt);
            }
        });
        Register.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lemon", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REGISTRATION");
        jLabel9.setToolTipText("");
        Register.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 390, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setText("Confirm Password");
        Register.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel11.setText("Password");
        Register.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setText("Address");
        Register.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setText("Age");
        Register.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        AddressTxt.setBackground(new java.awt.Color(204, 255, 255));
        Register.getContentPane().add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 210, 30));

        AgeTxt.setBackground(new java.awt.Color(204, 255, 255));
        Register.getContentPane().add(AgeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 210, 30));

        RegBut.setBackground(new java.awt.Color(229, 255, 204));
        RegBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegBut.setText("Register");
        RegBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButActionPerformed(evt);
            }
        });
        RegBut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegButKeyPressed(evt);
            }
        });
        Register.getContentPane().add(RegBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 100, 30));

        PrevBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/previous.png"))); // NOI18N
        PrevBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PrevBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevButActionPerformed(evt);
            }
        });
        Register.getContentPane().add(PrevBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        PassTxt.setBackground(new java.awt.Color(204, 255, 255));
        Register.getContentPane().add(PassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 210, 30));

        ConfirmPassTxt.setBackground(new java.awt.Color(204, 255, 255));
        ConfirmPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPassTxtActionPerformed(evt);
            }
        });
        Register.getContentPane().add(ConfirmPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 210, 30));

        NameTxt1.setBackground(new java.awt.Color(204, 255, 255));
        Register.getContentPane().add(NameTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel15.setText("Name");
        Register.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel16.setText("Contact");
        Register.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        PNTxt1.setBackground(new java.awt.Color(204, 255, 255));
        Register.getContentPane().add(PNTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel17.setText("State");
        Register.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        StateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Kedah", "Kelantan", "Malacca", "Negeri Sembilan", "Pahang", "Penang", "Perak", "Perlis", "Sabah", "Sarawak", "Selangor", "Terengganu", "Kuala Lumpur", "Labuan", "Putrajaya" }));
        StateComboBox.setSelectedIndex(-1);
        Register.getContentPane().add(StateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 210, 30));

        jLabel18.setText("Remarks: Hospital/ NGO leave a \"-\".");
        Register.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel19.setText("Email");
        Register.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        EmailTxt1.setBackground(new java.awt.Color(204, 255, 255));
        Register.getContentPane().add(EmailTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, 30));
        Register.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        note.setEnabled(false);
        Register.getContentPane().add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 50, -1));
        Register.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/registration2.jpg"))); // NOI18N
        Register.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -100, -1, -1));

        Login.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Login.setTitle("Login");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Login.setMinimumSize(new java.awt.Dimension(420, 320));
        Login.setPreferredSize(new java.awt.Dimension(420, 320));
        Login.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                LoginformWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                LoginformWindowOpened(evt);
            }
        });
        Login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PassTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTxt1ActionPerformed(evt);
            }
        });
        Login.getContentPane().add(PassTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 90, 30));

        LogBut.setBackground(new java.awt.Color(0, 0, 0));
        LogBut.setFont(new java.awt.Font("Lemon", 0, 12)); // NOI18N
        LogBut.setForeground(new java.awt.Color(255, 255, 204));
        LogBut.setText("Login");
        LogBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogButActionPerformed(evt);
            }
        });
        Login.getContentPane().add(LogBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 30));

        adminname.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        adminname.setForeground(new java.awt.Color(0, 0, 255));
        adminname.setText("Email");
        Login.getContentPane().add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, 30));

        jLabel13.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Password");
        Login.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        Login.getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 90, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel21.setText("User");
        Login.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, -1));

        ClearBut.setBackground(new java.awt.Color(255, 255, 255));
        ClearBut.setFont(new java.awt.Font("Lemon", 0, 12)); // NOI18N
        ClearBut.setForeground(new java.awt.Color(255, 0, 0));
        ClearBut.setText("Clear");
        ClearBut.setBorderPainted(false);
        ClearBut.setContentAreaFilled(false);
        ClearBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButActionPerformed(evt);
            }
        });
        Login.getContentPane().add(ClearBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 70, 20));

        jButton5.setFont(new java.awt.Font("Lemon", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Register");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Login.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/LoginAdmin.jpg"))); // NOI18N
        Login.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 110));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/blue.jpg"))); // NOI18N
        jLabel23.setText("jLabel6");
        Login.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CO-CO");
        setMinimumSize(new java.awt.Dimension(488, 588));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/COCO.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 340, 320));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("COVID Control, an app to help people in-need. ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 480, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("May the god bless all Malaysian during this pandemic, no matter who <3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 480, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("People in need ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 200, 60));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 102));
        jButton1.setText("Donator/ Helper");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButton1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jButton1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/cocobackground3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 490, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void registerFunc() 
    {
        tableMethod tm = new tableMethod();
        
        int count;
        String info[] = new String[9]; 
         
        info[0] = NameTxt1.getText(); 
        info[1] = AgeTxt.getText();
        info[2] = AddressTxt.getText();
        info[3] = String.valueOf(StateComboBox.getSelectedItem());
        info[4] = PNTxt1.getText();
        info[5] = EmailTxt1.getText();
        info[6] = note.getText();
        info[7] = PassTxt.getText();
        info[8] = ConfirmPassTxt.getText();
        
        if (info[1].equals("") || info[2].equals("") || info[3].equals("") || info[4].equals("") || info[5].equals("") || info[6].equals("")|| info[7].equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter All Information Before Register", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (info[8].equals(info[7])) //THE SAME STRING
        {
            String ss = info[0] + "\t" + info[1] + "\t" + info[2] + "\t" + info[3] + "\t" + info[4] + "\t" + info[5] + "\t" + info[6]+ "\t" + info[7];
          
            tm.appendData("User", ss);
            JOptionPane.showMessageDialog(this, "Registered Successfully");
            
            tm.foodbank(ss);
          
            Register.dispose();
        }
        else
        {
            ConfirmPassTxt.setText("");
            JOptionPane.showMessageDialog(this, "Invalid Password", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Helper.setLocationRelativeTo(null);
         Helper.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Receiver.setLocationRelativeTo(null);
         Receiver.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Helper.dispose();
        note.setText("2");
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HNGOButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HNGOButActionPerformed
        
        note.setText("3");
        Receiver.dispose();
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);
    }//GEN-LAST:event_HNGOButActionPerformed

    private void IndiButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndiButActionPerformed
        
        Receiver.dispose();
        note.setText("1");
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);
    }//GEN-LAST:event_IndiButActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        State st = new State();
        st.setLocationRelativeTo(null);
        st.setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void HelperWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_HelperWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_HelperWindowClosing

    private void RegButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButActionPerformed
        registerFunc();
    }//GEN-LAST:event_RegButActionPerformed

    private void RegButKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegButKeyPressed
        
    }//GEN-LAST:event_RegButKeyPressed

    private void PrevButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevButActionPerformed
        Register.dispose();

    }//GEN-LAST:event_PrevButActionPerformed

    private void ConfirmPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPassTxtActionPerformed
        registerFunc();
    }//GEN-LAST:event_ConfirmPassTxtActionPerformed

    private void RegisterformWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegisterformWindowClosing
        
    }//GEN-LAST:event_RegisterformWindowClosing

    private void RegisterformWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegisterformWindowOpened
        AgeTxt.requestFocus();
    }//GEN-LAST:event_RegisterformWindowOpened

    private void PassTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTxt1ActionPerformed
        
    }//GEN-LAST:event_PassTxt1ActionPerformed

    private void LogButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogButActionPerformed

        String email = NameTxt.getText();
        String password = String.valueOf(PassTxt1.getPassword());
        tableMethod tm = new tableMethod();
        Boolean flag = false;
        ArrayList<String> allData =  tm.readTable("User");
        for(int i=0; i<allData.size(); i++){
            
            String id = allData.get(i).split("\t")[0];
            String user = allData.get(i).split("\t")[6];
            String pw = allData.get(i).split("\t")[8];
           
            if(user.equals(email) && password.equals(pw)){
               
                flag = true;
                break;
            }
        }
       
        if(flag==true){
            this.dispose();
            switch(Integer.parseInt(note.getText())){
                case 1: 
                    IndividualReceiver ind = new IndividualReceiver();
                    ind.setLocationRelativeTo(null);
                    ind.NewIndividualReceiver(email);
                    ind.setVisible(true);
                    
                    break;
                
                case 2:
                    FoodBankMenu fbm = new FoodBankMenu(email);
                    fbm.setLocationRelativeTo(null);
                    fbm.setVisible(true);
                    break;
                    
                case 3: 
                    IndividualReceiver HNGO = new IndividualReceiver();
                    HNGO.setLocationRelativeTo(null);
                    HNGO.NewIndividualReceiver(email);
                    HNGO.setInvisible();
                    HNGO.setVisible(true);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password.\nPlease type again.", "Error", JOptionPane.ERROR_MESSAGE);
            NameTxt.setText("");
            PassTxt1.setText("");
        }
    }//GEN-LAST:event_LogButActionPerformed

    private void ClearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButActionPerformed
        NameTxt.setText("");
        PassTxt.setText("");
    }//GEN-LAST:event_ClearButActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        Login.dispose();
        
        Register.setLocationRelativeTo(null);
        Register.setVisible(true);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void LoginformWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LoginformWindowClosing
   
    }//GEN-LAST:event_LoginformWindowClosing

    private void LoginformWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LoginformWindowOpened
        NameTxt.requestFocus();
    }//GEN-LAST:event_LoginformWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JButton ClearBut;
    private javax.swing.JPasswordField ConfirmPassTxt;
    private javax.swing.JTextField EmailTxt1;
    private javax.swing.JButton HNGOBut;
    private javax.swing.JFrame Helper;
    private javax.swing.JButton IndiBut;
    private javax.swing.JButton LogBut;
    private javax.swing.JFrame Login;
    private static javax.swing.JTextField NameTxt;
    private javax.swing.JTextField NameTxt1;
    private javax.swing.JTextField PNTxt1;
    private javax.swing.JPasswordField PassTxt;
    private javax.swing.JPasswordField PassTxt1;
    private javax.swing.JButton PrevBut;
    private javax.swing.JFrame Receiver;
    private javax.swing.JButton RegBut;
    private javax.swing.JFrame Register;
    private javax.swing.JComboBox<String> StateComboBox;
    private static javax.swing.JLabel adminname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel note;
    // End of variables declaration//GEN-END:variables

}
