
package cocogui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;


public class FoodBankMenu extends javax.swing.JFrame {

    private String username;
    /**
     * Creates new form AdminMenu
     */
    String email;
    
    public FoodBankMenu(String email) {
        this.email = email;
        initComponents();
        showDate();
        showTime();
    }
    
    private FoodBankMenu(){
        
    }
    
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s =  new SimpleDateFormat("dd-MM-yyyy");
        DateLab.setText(s.format(d));        
    }
    
    void showTime(){
        new Timer(0, new ActionListener() //0 means no delay
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                Date d = new Date();
                SimpleDateFormat s =  new SimpleDateFormat("hh:mm:ss a");
                TimeLab.setText(s.format(d));   
            }
        }
        ).start();
    }

    //Accept username from other frame
   /*public void admin (String email)
    {
        this.email = email;
        WelcomeTxt.setText("WELCOME " + this.email);
    }*/

    //Exit function
 /* private void exit()
    {
        int choice = JOptionPane.showConfirmDialog(this, "Sign out to Main Menu?", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(choice == 0)
        {
            dispose();
            MainMenu mm = new MainMenu();
            mm.setLocationRelativeTo(null);
            mm.setVisible(true);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        OpenBut = new javax.swing.JButton();
        CloseNow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        TimeLab = new javax.swing.JLabel();
        DateLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FoodBank interface");
        setMinimumSize(new java.awt.Dimension(380, 430));
        setPreferredSize(new java.awt.Dimension(380, 430));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setMinimumSize(new java.awt.Dimension(370, 370));
        jPanel7.setPreferredSize(new java.awt.Dimension(370, 366));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpenBut.setBackground(new java.awt.Color(0, 0, 0));
        OpenBut.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        OpenBut.setForeground(new java.awt.Color(51, 255, 204));
        OpenBut.setText("Open now");
        OpenBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButActionPerformed(evt);
            }
        });
        jPanel7.add(OpenBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 260, 60));

        CloseNow.setBackground(new java.awt.Color(0, 0, 0));
        CloseNow.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        CloseNow.setForeground(new java.awt.Color(51, 51, 255));
        CloseNow.setText("Close now");
        CloseNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseNowActionPerformed(evt);
            }
        });
        jPanel7.add(CloseNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 260, 60));

        jLabel1.setFont(new java.awt.Font("Lemon", 0, 8)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Status: Currently open for donation and open for receiving ");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, 30));

        jLabel2.setFont(new java.awt.Font("Lemon", 0, 24)); // NOI18N
        jLabel2.setText("FOODBANK");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 153, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addImage/foodbank4.jpg"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 430, 380));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 350));

        jPanel11.setBackground(new java.awt.Color(255, 204, 229));
        jPanel11.setPreferredSize(new java.awt.Dimension(370, 366));

        TimeLab.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N
        TimeLab.setText("Time:");
        TimeLab.setToolTipText("");

        DateLab.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N
        DateLab.setText("Date:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeLab, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(DateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimeLab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseNowActionPerformed
       tableMethod tm = new tableMethod();
       tm.UpdateFoodBankClose(email);
        //save to database (0)
    }//GEN-LAST:event_CloseNowActionPerformed

    private void OpenButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButActionPerformed
       tableMethod tm = new tableMethod();
       tm.UpdateFoodBankOpen(email);
       
        //save to database(1)
    }//GEN-LAST:event_OpenButActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        Coco cc = new Coco();
        cc.setLocationRelativeTo(null);
        cc.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodBankMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodBankMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodBankMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodBankMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodBankMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseNow;
    private javax.swing.JLabel DateLab;
    private javax.swing.JButton OpenBut;
    private javax.swing.JLabel TimeLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
